### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "lottie-ios"

### ISSUE THREAD

**Issue by sallenhandong** [CloudlessMoon/react-native-template#1]
when i  pod install:
 CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.1.1, which depends on
      lottie-ios (~> 3.0.3)

**Comment by jiasongs** [comment]
> when i pod install:
> CocoaPods could not find compatible versions for pod "lottie-ios":
> In Podfile:
> lottie-ios (from `../node_modules/lottie-ios`)
> 
> ```
> lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.1.1, which depends on
>   lottie-ios (~> 3.0.3)
> ```
两种解决方案：
第一种，在package.json中将lottie-ios改为3.0.3
第二种，在node_modules找到lottie-react-native将lottie-react-native.podspec中的s.dependency 'lottie-ios'改为3.1.3
之所以改这个，是因为3.0.3版本的lottie-ios加载超过几百K的json文件会卡主线程
